### ISSUE TITLE
Create an AUR git package

### ISSUE THREAD

**Issue by Hikandy** [Nama/swayrst#11]
If this could be packaged into AUR (Arch user repository) git package, that would be really helpful for the arch users to install this directly

**Comment by Nama** [comment]
I think I'll do that, but at a later time.

Until then, you can just download the file from the newest Release and run it (more detailed on the README.md).
Or you can create a virtualenv, run `pip install git+https://github.com/Nama/sway-workspaces` and use it like `python -m sway_workspaces load MaWS`

**Comment by Nama** [comment]
@Hikandy sorry for the taking so long, I finally put it up on the AUR:
https://aur.archlinux.org/packages/swayrst-git
