### ISSUE TITLE
fails a simple save/load cycle

### ISSUE THREAD

**Issue by anarcat** [Nama/swayrst#14]
Interesting project! I really like the simplicity and adressing that sore gap that is annoyingly missing from sway. (IMHO, it was *also* missing from i3: the append_layout stuff was super hard to use and never really worked for me... anyways)

I've tried to use it, and couldn't make it run correctly. Here's a simple save/restore iteration:

```
anarcat@angela:swayrst$ ./swayrst/swayrst.py -v save basic
anarcat@angela:swayrst$ ./swayrst/swayrst.py -v load basic
Couldn't find: *notmuch-hello* - GNU Emacs at angela
Window Signal already in correct workspace 2
Couldn't find: foot
Couldn't find: swayrst/swayrst at main · Nama/swayrst — Mozilla Firefox
Couldn't find: foot
Total windows: 5
Left 5 untouched
Touched: 0:
Couldn't find 4:
anarcat@angela:swayrst$ 
```

so this isn't really working for me. I'm also a bit worried about the app writing and loading pickle files, those are really insecure and i don't quite see why we couldn't just use JSON or some more portable format there...

**Comment by Nama** [comment]
Are those not found windows already open? They need to be.

> I'm also a bit worried about the app writing and loading pickle files, those are really insecure and i don't quite see why we couldn't just use JSON or some more portable format there...

We save the workspaces as objects from the i3ipc module, so they can be used again without comparing and searching for all the workspaces and windows:
https://github.com/Nama/swayrst/blob/main/swayrst/swayrst.py#L136

I use json where I can (two lines above that), but that part is way better with pickle files.
